# Generated by Django 5.0.3 on 2024-03-19 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctorlogin', '0003_alter_doctor_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profile_picture',
            field=models.ImageField(default=None, max_length=500, null=True, upload_to='profile_pictures/'),
        ),
    ]
