# Generated by Django 5.0.3 on 2024-03-18 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('doctor', models.CharField(choices=[('dr-smith', 'Dr. Smith'), ('dr-jones', 'Dr. Jones'), ('dr-wilson', 'Dr. Wilson'), ('dr-miller', 'Dr. Miller'), ('dr-anderson', 'Dr. Anderson'), ('dr-brown', 'Dr. Brown'), ('dr-davis', 'Dr. Davis'), ('dr-evans', 'Dr. Evans'), ('dr-garcia', 'Dr. Garcia'), ('dr-hall', 'Dr. Hall'), ('dr-jackson', 'Dr. Jackson'), ('dr-kelly', 'Dr. Kelly'), ('dr-lee', 'Dr. Lee'), ('dr-martin', 'Dr. Martin'), ('dr-nelson', 'Dr. Nelson'), ('dr-owens', 'Dr. Owens'), ('dr-patel', 'Dr. Patel'), ('dr-ross', 'Dr. Ross'), ('dr-taylor', 'Dr. Taylor'), ('dr-white', 'Dr. White')], max_length=20)),
                ('date_and_time', models.DateTimeField()),
            ],
        ),
    ]
